---
- hosts: all
  become: true
  become_user: root

  tasks:
    - name: "Generate ja_JP.UTF-8 locale"
      locale_gen:
        name: ja_JP.UTF-8
        state: present

    - name: "set-locale"
      shell: update-locale LANG=ja_JP.UTF-8

    - name: Set timezone to Asia/Tokyo
      file:
        src: /usr/share/zoneinfo/Asia/Tokyo
        path: /etc/localtime
        state: link
        force: yes
      notify:
        - update timezone

    - name: "put /etc/sudoers.d/{{ sudo_user_name }}"
      template:
        src: etc/sudoers.d/user_sudo
        dest: "/etc/sudoers.d/{{ sudo_user_name }}"
        owner: root
        group: root
        mode: 0440
        backup: true

    - name: Install Ubuntu common dev tool packages
      ansible.builtin.package:
        name:
          - ansible
          - bash-completion
          - bmon
          - curl
          - git
          - htop
          - iftop
          - iotop
          - iproute2
          - iputils-ping
          - iptraf
          - iptraf-ng
          - net-tools
          - nmap
          - sudo
          - sysstat
          - telnet
          - tree
          - unzip
          - vim
          - wget
          - zip
          - python3-pip
        state: present

    - name: "create {{ user_name }} .ssh/ dicrectory"
      file:
        path: "/home/{{ user_name }}/.ssh"
        state: directory
        mode: 0700
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: "create {{ user_name }} .aws/ dicrectory"
      file:
        path: "/home/{{ user_name }}/.aws"
        state: directory
        mode: 0700
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: ".aws/config"
      template:
        src: home/.aws/config
        dest: "/home/{{ user_name }}/.aws/config"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0600
        backup: true
    #######################################################################################################################
    # ホームディレクトリ関連
    #######################################################################################################################
    - name: set .bashrc
      template:
        src: home/.bashrc
        dest: "/home/{{ user_name }}/.bashrc"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: set .bash_alias
      template:
        src: home/.bash_aliases.j2
        dest: "/home/{{ user_name }}/.bash_aliases"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: set .profile
      template:
        src: home/.profile
        dest: "/home/{{ user_name }}/.profile"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: set .bash_profile
      template:
        src: home/.bash_profile
        dest: "/home/{{ user_name }}/.bash_profile"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: "set {{ user_name }} user .ssh/config"
      template:
        src: "home/.ssh/config.j2"
        dest: "/home/{{ user_name }}/.ssh/config"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: 0600
        backup: true

    - name: set wsl .gitconfig.j2
      template:
        src: home/.gitconfig.j2
        dest: "/home/{{ user_name }}/.gitconfig"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: set wsl .gitignore_global
      template:
        src: home/.gitignore_global.j2
        dest: "/home/{{ user_name }}/.gitignore_global"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: apt add golang repository
      ansible.builtin.apt_repository:
        repo: ppa:longsleep/golang-backports

    - name: Install golang
      ansible.builtin.package:
        name:
          - golang
          - golang-go
        state: present

    - name: Install nodejs and npm
      ansible.builtin.package:
        name:
          - nodejs
          - npm
        state: present

    - name: npmでgo-task/cliをグローバルインストール
      npm:
        name: "@go-task/cli"
        global: yes
        state: present

    - name: npmで@anthropic-ai/claude-codeをグローバルインストール
      npm:
        name: "@anthropic-ai/claude-code"
        global: yes
        state: present

    - name: "git safe directory at /home/{{ user_name }}/git/scripts"
      shell: "git config --global --add safe.directory /home/{{ user_name }}/scripts"
      tags: git_checkout

    - name: Check if scripts directory exists
      stat:
        path: "/home/{{ user_name }}/git/scripts"
      register: scripts_dir_stat
      tags: git_checkout

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ user_name }}/git/scripts"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: scripts_dir_stat.stat.exists
      tags: git_checkout

    - name: Clone scripts github repository
      become: yes
      become_user: '{{ user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/scripts.git
        dest: "/home/{{ user_name }}/git/scripts"
        clone: yes
        update: yes
        key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
        accept_hostkey: true
      tags: git_checkout

    - name: "git safe directory at /home/{{ user_name }}/git/scripts"
      shell: "git config --global --add safe.directory /home/{{ user_name }}/git/scripts"
      tags: git_checkout

    - name: Check if infra directory exists
      stat:
        path: "/home/{{ user_name }}/git/infra"
      register: infra_dir_stat
      tags: git_checkout

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ user_name }}/git/infra"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: infra_dir_stat.stat.exists
      tags: git_checkout

    - name: Clone infra github repository
      become: yes
      become_user: '{{ user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/infra.git
        dest: "/home/{{ user_name }}/git/infra"
        clone: yes
        update: yes
        key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
        accept_hostkey: true
      tags: git_checkout

    - name: "git safe directory at /home/{{ user_name }}/git/blog.toshi.click"
      shell: "git config --global --add safe.directory /home/{{ user_name }}/git/blog.toshi.click"
      tags: git_checkout

    - name: Check if blog.toshi.click directory exists
      stat:
        path: "/home/{{ user_name }}/git/blog.toshi.click"
      register: blog_dir_stat
      tags: git_checkout

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ user_name }}/git/blog.toshi.click"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: blog_dir_stat.stat.exists
      tags: git_checkout

    - name: Clone blog.toshi.click github repository
      become: yes
      become_user: '{{ user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/blog.toshi.click.git
        dest: "/home/{{ user_name }}/git/blog.toshi.click"
        clone: yes
        update: yes
        key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
        accept_hostkey: true
      tags: git_checkout

    - name: "git safe directory at /home/{{ user_name }}/git/CurriculumVitae"
      shell: "git config --global --add safe.directory /home/{{ user_name }}/git/CurriculumVitae"
      tags: git_checkout

    - name: Check if CurriculumVitae directory exists
      stat:
        path: "/home/{{ user_name }}/git/CurriculumVitae"
      register: cv_dir_stat
      tags: git_checkout

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ user_name }}/git/CurriculumVitae"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: cv_dir_stat.stat.exists
      tags: git_checkout

    - name: Clone CurriculumVitae github repository
      become: yes
      become_user: '{{ user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/CurriculumVitae.git
        dest: "/home/{{ user_name }}/git/CurriculumVitae"
        clone: yes
        update: yes
        key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
        accept_hostkey: true
      tags: git_checkout

    - name: "git safe directory at /home/{{ user_name }}/git/ansible_for_wsl"
      shell: "git config --global --add safe.directory /home/{{ user_name }}/git/ansible_for_wsl"
      tags: git_checkout

    - name: Check if ansible_for_wsl directory exists
      stat:
        path: "/home/{{ user_name }}/git/ansible_for_wsl"
      register: ansible_wsl_dir_stat
      tags: git_checkout

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ user_name }}/git/ansible_for_wsl"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: ansible_wsl_dir_stat.stat.exists
      tags: git_checkout

    - name: Clone ansible_for_wsl github repository
      become: yes
      become_user: '{{ user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/ansible_for_wsl.git
        dest: "/home/{{ user_name }}/git/ansible_for_wsl"
        clone: yes
        update: yes
        key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
        accept_hostkey: true
      tags: git_checkout

    - name: "git safe directory at /home/{{ user_name }}/git/develop"
      shell: "git config --global --add safe.directory /home/{{ user_name }}/git/develop"
      tags: git_checkout

    - name: Check if develop directory exists
      stat:
        path: "/home/{{ user_name }}/git/develop"
      register: develop_dir_stat
      tags: git_checkout

    - name: すでにクローン済みの場合ディレクトリとファイルのパーミッションを再帰的に変更する
      file:
        path: "/home/{{ user_name }}/git/develop"
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        recurse: yes
      when: develop_dir_stat.stat.exists
      tags: git_checkout

    - name: Clone develop github repository
      become: yes
      become_user: '{{ user_name }}'
      ansible.builtin.git:
        repo: git@github.com:toshibe678/develop.git
        dest: "/home/{{ user_name }}/git/develop"
        clone: yes
        update: yes
        key_file: "/home/{{ user_name }}/.ssh/id_ed25519"
        accept_hostkey: true
      tags: git_checkout
